language: node_js
sudo: true
before_install:
  - "npm -g install npm"
script:
  - "sudo $(which node) $(which npm) test"
os:
  - osx
  - linux
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
node_js:
  - "4"
  - "6"
  - "0.10"
  - "5"
  - "0.12"
